language: node_js
node_js:
  - '12'

cache:
  directories:
    - ./node_modules

install:
  - npm install

script:
  - npm run-script build:prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  keep_history: true
  on:
    branch: master
